# Generated by Django 3.2.9 on 2021-11-27 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderType', models.CharField(max_length=4)),
                ('ticker', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transactionDate', models.DateTimeField(default=datetime.datetime(2021, 11, 27, 15, 59, 13, 541832), verbose_name='transaction date')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
