# Generated by Django 3.2.9 on 2021-11-28 00:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='transactionDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 27, 16, 0, 59, 733858), verbose_name='transaction date'),
        ),
    ]
